### ISSUE TITLE
Wifi threads crash in Ota mode

### ISSUE THREAD

**Issue by dapeng0512** [espressif/esp-hal-3rdparty#1]
when i enable OTA with mcuboot in nuttx， the system will crash at ‘esp_wifi_init_internal’ functon，i noticed that this function does not provide source code and cannot analyze specific problems. Does anyone have this problem?

esp-hal-3rdparty version is latest (2fbc8a025275d68833cdfef490377048538de57a) in release/v5.1.c branch

this is full start log.

<img width="1061" alt="image" src="https://github.com/espressif/esp-hal-3rdparty/assets/15180245/dbaa8542-dd3a-4b46-9050-1214399f41b3">

Anyway, Wifi threads in non-OTA mode are not crashing back

tks.

**Comment by tmedicci** [comment]
Hi! Could you please report the issue on NuttX project as stated in [`README.md`](https://github.com/espressif/esp-hal-3rdparty/blob/main/README.md?plain=1#L10)?

Also, please provide more information on how the issue can be reproduced.

**Comment by dapeng0512** [comment]
> Hi! Could you please report the issue on NuttX project as stated in [`README.md`](https://github.com/espressif/esp-hal-3rdparty/blob/main/README.md?plain=1#L10)?
> 
> Also, please provide more information on how the issue can be reproduced.

hi tmedicci,  thank you for your reply.

I did not submit an issue to the Nuttx project. 
Because I was positioning problems with the 'esp_wifi_init_internal' function in esp-hal-3rdparty, but found that this part of the code was not open source, personal guess should be the result of this part of the code adapted to the mcuboot partition problems. But I can't see the code, I can't be sure

Replication step:

1. ./tools/configure.sh esp32s3-devkit:wifi

2. modify config
CONFIG_ESP32S3_HAVE_OTA_PARTTION=y
CONFIG_ESP32S3_STORAGE_MTD_OFFSET=0x250000
CONFIG_ESP32S3_STORAGE_MTD_SIZE=0x100000

others, use default

3. build bootloader and nuttx
4. flash

tks.

**Comment by tmedicci** [comment]
> > Hi! Could you please report the issue on NuttX project as stated in [`README.md`](https://github.com/espressif/esp-hal-3rdparty/blob/main/README.md?plain=1#L10)?
> > Also, please provide more information on how the issue can be reproduced.
> 
> hi tmedicci, thank you for your reply.
> 
> I did not submit an issue to the Nuttx project. Because I was positioning problems with the 'esp_wifi_init_internal' function in esp-hal-3rdparty, but found that this part of the code was not open source, personal guess should be the result of this part of the code adapted to the mcuboot partition problems. But I can't see the code, I can't be sure
> 
> Replication step:
> 
> 1. ./tools/configure.sh esp32s3-devkit:wifi
> 2. modify config
>    CONFIG_ESP32S3_HAVE_OTA_PARTTION=y
>    CONFIG_ESP32S3_STORAGE_MTD_OFFSET=0x250000
>    CONFIG_ESP32S3_STORAGE_MTD_SIZE=0x100000
> 
> others, use default
> 
> 3. build bootloader and nuttx
> 4. flash
> 
> tks.

Hi @dapeng0512 , I got it. We highly appreciate your report, but once this is related to NuttX somehow, we only can provide support by associating it with the OS. Could you please open the issue in NuttX project?

I'll investigate as soon as possible.

Thanks!
